### ISSUE TITLE
help on usage

### ISSUE THREAD

**Issue by wesyah234** [lcherone/SimplePOPCDN#6]
Hi.  I think what you've built here is what I'm looking for... But I'm not sure exactly how to set it up...

So, I install this index.php on my caching server.. but how do I configure the urls on my origin server .
example:
http://mywebsite.com/image/someimage.jpg
and my caching server is:
http://mycdn.com/index.php

So would I access:
http://mycdn.com/index.php/image/someimage.jpg
and should it then pull down mywebsite.com/image/someimage.jpg
cache it locally
and then serve it up?

I'm thinking this is how it would work but I don't see any concrete example of how to hook everything together.
Thanks!
Wes

**Comment by lcherone** [comment]
Yes your correct thats how it works, though you will need to have rewrite enabled on the server for it to work, this way the url becomes `http://mycdn.com/image/someimage.jpg` (see .htaccess)

The idea is to simply replace the domain name in your application when setting up the urls you wish to cache on the cdn.

On the cdn side, when a request comes in it will use the domain supplied in the class construct to fetch the asset and store locally.

`new SimplePOPCDN('http://mywebsite.com', './cache/');`

Hope it help, its nice to see someone interested in my old code, making use of an old boot. :)

**Comment by wesyah234** [comment]
hey, I'm glad I found your code.. it's what I've been thinking of building for a long time and I finally got around to searching to see if someone had done it already!

ok, I got rewrite working and it's sort of working.. but I'm curious.. it seems all my fetches through the CDN are getting 307 redirects... so if the fetch to the CDN is just returning a redirect then it isn't actually fetching the resource through the CDN, because it seems as if my browser is fetching the resource from the origin after getting the 307.... can you explain?

**Comment by lcherone** [comment]
Check there are write permissions on the `./cache` folder, sounds like the files are not being written to the cache folder after pulled from the origin.

**Comment by wesyah234** [comment]
Yes, that was the issue... I also commented out the 307 redirect but I can probably put that back as it was the cache write permissions that was probably the issue.. So why does it do the redirect? Also, I had to add some new mime types for font downloads that weren't handled.. when I get things set up properly I can submit a pull request for that change.

**Comment by lcherone** [comment]
Yes put the redirect back.. it sets the `307 Moved Temporarily` redirect because the cdn wont have the asset first time around, the initial request is to trigger the pull, upon subsequent request it will have the asset and serve it.

Submitting a pull request for the font handling additions that would be great, thank you.

Ive used this class with a few tweeks in the past to cache all sorts of 3rd party assets it works well, could do with RANGE headers added so it can handle video ect.

Cheers

**Comment by wesyah234** [comment]
Will do.. that makes sense!... with commercial CDNs I've used, they just fetch and also return the asset on the first call (at least that's what I thought they did) but doing the redirect on the first time seems like it might be faster overall for the end user.

**Comment by lcherone** [comment]
@wesyah234 Recent commit fixes 307 redirect, it only happens now if it fails to fetch the file. And mime types can be added more easily now.

**Comment by wesyah234** [comment]
excellent!! great changes... I like the default you have in there now to application/octet-stream if the type is not found.. that will make it run much better!... So have you thought about how this could be run for multiple websites?  I have an idea but I'm sure you might have a better way of doing it.  My idea is to have a convention of mycdn.mysite.com, and the cdn script can pull off mycdn, and then know that it's a CDN for mysite.com, and put the cache files into a subdirectory named after mysite.com... and also then the script can have a configuration of the "allowed sites" that it will provide cdn service for, to prevent others from pointing at it for CDN.... just an idea because I'm thinking of setting this up for multiple sites.

**Comment by lcherone** [comment]
The script can handle multiple sites you just pass it different construct values.

For example, using the servers host/domain name from the headers:
```
<?php
// set your sites, could be from db
$sites = [
    'cdn.example.com',
    'cdn.1example.com',
    'cdn.2example.com'
];

// check the hosts name is in the sites list
if (in_array($_SERVER['HTTP_HOST'], $sites)) {
    $host = parse_url($_SERVER['HTTP_HOST'], PHP_URL_HOST);
    $host = explode('.', $host);
    
    //
    $origin = $host[1].'.'.$host[2];

    // is origin https    
    $https = false;
    if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
        $https = true;
    }
    elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || !empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on') {
        $https = true;
    }
    $https = $https ? 'https' : 'http';
    
    // check cache exists
    if (!file_exists('./cache/'.$origin)) {
        if (!mkdir('./cache/'.$origin, 0777, true)) {
            exit(header('Location: '.$https.'://'.$origin.$_SERVER['REQUEST_URI'], true, 307));
        }
    }
    
    new SimplePOPCDN($https.'://'.$origin, './cache/'.$origin, null, 2592000);
    
} else {
    header($_SERVER['SERVER_PROTOCOL'].' 404 Not Found');
}

```

**Comment by wesyah234** [comment]
Thanks this will work well with a few mods!  I'll post my version back here when it's working well.
