### ISSUE TITLE
having a problem with icon sets

### ISSUE THREAD

**Issue by wesyah234** [lcherone/SimplePOPCDN#9]
I'm on a wordpress site that uses a theme that utilizes Font Awesome icon sets.  The following html is supposed to show a "money" icon however when my page is loaded through the CDN it doesn't display properly... could there be an issue with UTF-8 /unicode? or with the CSS?

<i style="border-color:#ffffff;border-width:0px;background-color:rgba(255,255,255,0);height:68px;width:68px;line-height:68px;border-radius:50%;color:#990413;font-size:34px;" class="fa fontawesome-icon fa-money circle-yes"></i>

this is the documentation page for the icon that fails to display when the site is loaded via the CDN:
http://fontawesome.io/icon/money/

**Comment by lcherone** [comment]
Are you getting any browser console errors (404's), when you say "it doesn't display properly", does that mean its not displaying at all?

Can you access the font awesome "font" files directly? 

It may well be a encoding issue try appending to the content type header.

`header("Content-Type: {$this->request_info['mime']};charset=utf-8");`

**Comment by wesyah234** [comment]
I tried adding utf-8 but it didn't help.  But I did notice this in the Console:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://mycdn.../wp-content/themes/Avada/assets/fonts/fontawesome/fontawesome-webfont.woff?v=4.7.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).  (unknown)
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: http://mycdn.../wp-content/themes/Avada/assets/fonts/fontawesome/fontawesome-webfont.woff?v=4.7.0  font-awesome.css:4:14
GET 
http://mycdn.../wp-content/themes/Avada/assets/fonts/fontawesome/fontawesome-webfont.ttf [HTTP/1.1 200 OK 543ms]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://mycdn/wp-content/themes/Avada/assets/fonts/icomoon/icomoon.woff. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).  (unknown)
downloadable font: download failed (font-family: "icomoon" style:normal weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: http://mycdn.../wp-content/themes/Avada/assets/fonts/icomoon/icomoon.woff  style.min.css:1:184925
downloadable font: no supported format found (font-family: "icomoon" style:normal weight:normal stretch:normal src index:4) source: (end of source list)

**Comment by lcherone** [comment]
Yeah that would be it, thank you for the pull request. Closing issue.
